language: python

python:
  - "2.7"

install:
#  - sudo apt-get update
  - sudo apt-get install -y python-lxml
  - pip install -r requirements.txt
  - python setup.py install

script:
  - dpkg -l | grep libxml
  - cd tests
  - python test_ts.py
