language: python

python:
  - "2.7"

install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y libxml2 libxml2-dev
  - pip install -r requirements.txt
  - python setup.py install

script:
  - cd tests
  - python test_ts.py
